import { Program, FAQItem, StatItem, TestimonialItem, MemberItem } from './types';

export const STATS_DATA: StatItem[] = [
  {
    id: 'stat-sampah',
    label: 'Minyak & Anorganik',
    value: 1450,
    suffix: ' kg',
    iconName: 'Trash2',
    colorClass: 'text-brand-primary bg-brand-light/30 border-brand-medium/20',
    accentClass: 'bg-brand-accent',
  },
  {
    id: 'stat-pohon',
    label: 'Rak Vertikultur & TOGA',
    value: 350,
    suffix: ' bibit',
    iconName: 'Leaf',
    colorClass: 'text-brand-deep bg-brand-light border-brand-medium/30',
    accentClass: 'bg-brand-primary',
  },
  {
    id: 'stat-kk',
    label: 'Biopori Terpasang',
    value: 45,
    suffix: ' titik',
    iconName: 'Wrench',
    colorClass: 'text-brand-primary bg-bg-light border-border-soft',
    accentClass: 'bg-brand-medium',
  },
  {
    id: 'stat-relawan',
    label: 'Kader & Ibu PKK Terlatih',
    value: 85,
    suffix: ' orang',
    iconName: 'Award',
    colorClass: 'text-brand-deep bg-brand-medium/20 border-brand-medium/30',
    accentClass: 'bg-brand-deep',
  },
];

export const PROGRAMS_DATA: Program[] = [
  {
    id: 'prog-1',
    title: 'Vertical Garden Menggunakan Botol Bekas untuk Penanaman Sayuran',
    category: 'farming',
    status: 'aktif',
    description: 'Inisiatif pembuatan vertical garden dari botol plastik bekas untuk mengoptimalkan penanaman sayuran di lahan terbatas.',
    fullDescription: 'Program ini berfokus pada pemanfaatan limbah botol plastik bekas sebagai wadah tanaman sayuran secara vertikal di Kelompok Tani Sami Mulyo. Vertical garden ini dirancang untuk mengatasi keterbatasan lahan horizontal sekaligus mengurangi sampah plastik rumah tangga secara kreatif.',
    date: 'Sabtu, 4 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Nata',
    impact: 'Terbentuknya vertical garden, pemanfaatan limbah botol plastik, dan penanaman bibit sayuran.',
    iconName: 'Sprout',
  },
  {
    id: 'prog-2',
    title: 'Pendampingan Penanaman Sayuran Menggunakan Media Tanam Campuran dalam Wadah Botol Plastik Bekas sebagai Teknologi Tepat Guna Pengelolaan Sampah dan Ketahanan Pangan',
    category: 'farming',
    status: 'aktif',
    description: 'Pendampingan teknis bercocok tanam menggunakan botol plastik bekas dengan formula media tanam campuran.',
    fullDescription: 'Kegiatan pendampingan intensif bagi warga dalam mengolah media tanam campuran (tanah, kompos, sekam bakar) untuk ditanam pada wadah botol bekas. Ini merupakan bentuk teknologi tepat guna guna menunjang kemandirian pangan keluarga serta pemanfaatan limbah plastik.',
    date: 'Sabtu, 4 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Vada',
    impact: 'Terlaksananya penanaman sayuran pada botol plastik bekas dengan media tanam campuran serta meningkatnya pemanfaatan limbah plastik untuk mendukung ketahanan pangan rumah tangga.',
    iconName: 'Leaf',
  },
  {
    id: 'prog-3',
    title: 'Edukasi Gadget dan Aktivitas Kreatif Remaja Berbasis Lingkungan',
    category: 'edukasi',
    status: 'aktif',
    description: 'Edukasi bijak menggunakan gawai dan bimbingan kreativitas berbasis kelestarian lingkungan bagi remaja.',
    fullDescription: 'Pelatihan interaktif bagi anak-anak dan remaja di Kelurahan Cokrodiningratan untuk memaksimalkan fungsi positif gadget dan melatih kreativitas dengan aktivitas fisik bertema pelestarian lingkungan hidup sekitar.',
    date: 'Selasa, 7 Juli 2026',
    location: 'Kelurahan Cokrodiningratan',
    coordinator: 'Chani',
    impact: 'Remaja dan siswa SD mampu menggunakan gadget secara bijak serta aktif dalam kegiatan kreatif berbasis lingkungan.',
    iconName: 'Smartphone',
  },
  {
    id: 'prog-4',
    title: 'Sosialisasi dan Bantuan Pendaftaran QRIS serta Linktree untuk UMKM di Cokrodiningratan',
    category: 'edukasi',
    status: 'aktif',
    description: 'Digitalisasi pembayaran dan pemasaran bagi pelaku UMKM melalui pendaftaran QRIS dan Linktree.',
    fullDescription: 'Upaya percepatan digitalisasi ekonomi lokal melalui pendampingan pendaftaran QRIS bagi pelaku usaha mikro serta pembuatan link profil promosi (Linktree) agar UMKM di Cokrodiningratan dapat bersaing secara digital.',
    date: 'Rabu, 8 Juli 2026',
    location: 'Kelurahan Cokrodiningratan',
    coordinator: 'Chani',
    impact: 'Pelaku UMKM berhasil mendaftarkan QRIS dan membuat Linktree sebagai media transaksi serta promosi digital.',
    iconName: 'QrCode',
  },
  {
    id: 'prog-5',
    title: 'Digitalisasi dan Branding UMKM',
    category: 'edukasi',
    status: 'aktif',
    description: 'Peningkatan nilai jual produk lokal melalui bimbingan branding, visual identitas, dan manajemen usaha.',
    fullDescription: 'Pelatihan komprehensif bagi pemilik UMKM mengenai cara membangun identitas visual produk (branding), teknik pengemasan yang menarik, serta metode manajemen usaha sederhana agar meningkatkan branding dan penjualan usaha.',
    date: 'Rabu, 8 Juli 2026',
    location: 'Omah Ijo Cokrodiningratan',
    coordinator: 'Nata',
    impact: 'Pelaku UMKM mampu mengelola usaha dengan lebih baik sehingga meningkatkan branding usaha.',
    iconName: 'Sparkles',
  },
  {
    id: 'prog-6',
    title: 'Pendampingan Pembuatan Herbarium Berbahan Dasar Limbah Gulma sebagai Media Edukasi Lingkungan',
    category: 'edukasi',
    status: 'aktif',
    description: 'Pemanfaatan gulma liar menjadi herbarium kering bernilai edukatif untuk mengenalkan keanekaragaman hayati.',
    fullDescription: 'Eksperimen menyenangkan bersama siswa-siswi SD Negeri Jetis 1 dalam mengawetkan tanaman gulma liar menjadi herbarium kering. Kegiatan ini bertujuan mengenalkan botani dasar, keanekaragaman hayati, sekaligus mengubah gulma yang tidak terpakai menjadi media belajar yang edukatif.',
    date: 'Kamis, 16 Juli 2026',
    location: 'SD Negeri Jetis 1',
    coordinator: 'Vada',
    impact: 'Herbarium berbahan limbah gulma sebagai media edukasi lingkungan serta meningkatnya pemahaman peserta mengenai keanekaragaman tumbuhan dan pemanfaatan gulma.',
    iconName: 'Bookmark',
  },
  {
    id: 'prog-7',
    title: 'Papan Permainan Edukasi Pilah Sampah Sejak Dini',
    category: 'sampah',
    status: 'aktif',
    description: 'Pengenalan jenis sampah anorganik dan organik melalui metode permainan edukatif interaktif.',
    fullDescription: 'Pembuatan dan penyerahan media belajar interaktif berupa papan permainan pilah sampah sejak dini bagi anak-anak. Siswa diajarkan memilah kategori sampah secara menyenangkan menggunakan pin edukasi.',
    date: 'Jumat, 17 Juli 2026',
    location: 'SD Negeri Jetis 1',
    coordinator: 'Nata',
    impact: 'Media permainan interaktif berupa papan dan pin edukasi pemilahan sampah.',
    iconName: 'Gamepad2',
  },
  {
    id: 'prog-8',
    title: 'Pesona Kulit Bawang: Dari Kulit Bawang Merah dan Bawang Putih sebagai Pestisida Nabati',
    category: 'farming',
    status: 'aktif',
    description: 'Formulasi pestisida ramah lingkungan bebas bahan kimia buatan dari pemanfaatan kulit bawang.',
    fullDescription: 'Workshop pembuatan pestisida cair alami (pestisida nabati) dengan memanfaatkan limbah sisa bumbu dapur berupa kulit bawang merah dan bawang putih. Cairan ini berfungsi sebagai pengusir hama tanaman Kelompok Tani Sami Mulyo.',
    date: 'Sabtu, 18 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Gabriella Ramadhina Haris',
    impact: 'Pestisida nabati berbahan kulit bawang merah dan bawang putih.',
    iconName: 'FlaskConical',
  },
  {
    id: 'prog-9',
    title: 'Mastering The Maggot',
    category: 'farming',
    status: 'aktif',
    description: 'Panduan infografis komprehensif penentuan nutrisi optimal pertumbuhan maggot BSF.',
    fullDescription: 'Penyusunan dan edukasi panduan praktis (infografis) mengenai komposisi pakan dan nutrisi yang tepat bagi budidaya maggot Black Soldier Fly (BSF) sebagai agen pengurai sampah organik yang optimal.',
    date: 'Sabtu, 18 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Gabriella Ramadhina Haris',
    impact: 'Infografis optimalisasi nutrisi untuk budidaya maggot.',
    iconName: 'FileText',
  },
  {
    id: 'prog-10',
    title: 'Maggot Box Alternatif dari Galon dan Botol Bekas',
    category: 'sampah',
    status: 'aktif',
    description: 'Pembuatan wadah biokonversi maggot BSF skala rumah tangga memanfaatkan galon plastik tak terpakai.',
    fullDescription: 'Reka cipta wadah maggot box sederhana dari limbah galon dan botol plastik bekas sebagai komposter biopori mini alternatif yang murah, rapi, dan mudah diaplikasikan warga di pekarangan rumah.',
    date: 'Sabtu, 18 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo RW 03',
    coordinator: 'Amanulloh Bariq N.',
    impact: 'Maggot box alternatif berbahan galon dan botol bekas.',
    iconName: 'Boxes',
  },
  {
    id: 'prog-11',
    title: 'Sosialisasi dan Edukasi Budidaya Maggot (Nutrisi Tepat untuk Maggot)',
    category: 'edukasi',
    status: 'aktif',
    description: 'Penyuluhan budidaya maggot BSF dan penyerahan leaflet edukatif bagi warga Cokrodiningratan.',
    fullDescription: 'Sosialisasi massal guna mengedukasi warga tentang siklus hidup BSF, pentingnya pengelolaan sampah organik dengan maggot, serta penyerahan leaflet, poster, atau modul edukatif sebagai referensi mandiri warga.',
    date: 'Sabtu, 18 Juli 2026',
    location: 'Pendopo Kelurahan Cokrodiningratan',
    coordinator: 'Nata',
    impact: 'Masyarakat memahami nutrisi yang tepat untuk pertumbuhan maggot serta tersedianya media edukasi berupa leaflet, poster, atau modul.',
    iconName: 'BookOpen',
  },
  {
    id: 'prog-12',
    title: 'Pendampingan Pembuatan Pestisida Nabati Berbahan Limbah Tembakau Dikombinasikan dengan Penanaman Sayur dan TOGA sebagai Upaya Pertanian Ramah Lingkungan',
    category: 'farming',
    status: 'aktif',
    description: 'Ekstraksi nikotin limbah tembakau menjadi pestisida nabati pengusir hama tanaman kebun sayur.',
    fullDescription: 'Program integratif pendampingan ekstraksi limbah tembakau (sisa puntung/daun) menjadi pestisida alami yang ramah lingkungan, digabungkan dengan penerapan pertanian lestari melalui penanaman sayur dan TOGA.',
    date: 'Sabtu, 18 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Vada',
    impact: 'Pestisida nabati berbahan limbah tembakau berhasil dibuat, serta terlaksananya penanaman sayuran dan TOGA sebagai penerapan pertanian ramah lingkungan.',
    iconName: 'Droplet',
  },
  {
    id: 'prog-13',
    title: 'Infografis Profil Kampung Hijau',
    category: 'penghijauan',
    status: 'aktif',
    description: 'Penyusunan rangkuman pencapaian, tata kelola, dan identitas visual Kampung Hijau RW 03.',
    fullDescription: 'Pembuatan poster infografis yang merangkum data profil, keunikan, tata kelola, dan identitas visual ekologis di Kampung Hijau Sami Mulyo RW 03 sebagai media informasi dan promosi publik.',
    date: 'Sabtu, 25 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo RW 03',
    coordinator: 'Amanulloh Bariq N.',
    impact: 'Poster infografis profil Kampung Hijau.',
    iconName: 'Image',
  },
  {
    id: 'prog-14',
    title: 'Kampung Hijau: Penataan dan Edukasi Ruang Hijau',
    category: 'penghijauan',
    status: 'aktif',
    description: 'Penataan ulang (landscaping) zonasi tanaman dan pelabelan nama kategori tanaman.',
    fullDescription: 'Aksi penataan kembali tata letak tanaman di kebun kelompok tani, pembagian kategori tanaman (sayur, obat, hias), agar lingkungan tertata rapi dan bernilai edukasi tinggi.',
    date: 'Sabtu, 25 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Nata',
    impact: 'Seluruh tanaman di Kelompok Tani Sami Mulyo tertata berdasarkan kategorinya.',
    iconName: 'Compass',
  },
  {
    id: 'prog-15',
    title: 'Pendampingan Pelatihan Menggunakan Galon Plastik Bekas sebagai Teknologi Tepat Guna Pemanfaatan Sampah untuk Mendukung Kemandirian Pangan dan Lingkungan Hijau Masyarakat',
    category: 'farming',
    status: 'aktif',
    description: 'Pelatihan modifikasi galon plastik bekas menjadi pot tanaman produktif jangka panjang.',
    fullDescription: 'Workshop pemanfaatan limbah galon plastik bekas sebagai teknologi tepat guna wadah bercocok tanam sayuran dan tanaman obat keluarga (TOGA) untuk mewujudkan kemandirian pangan tingkat rumah tangga.',
    date: 'Minggu, 26 Juli 2026',
    location: 'Kelompok Tani Sami Mulyo',
    coordinator: 'Vada',
    impact: 'Wadah tanam berbahan galon plastik bekas berhasil dimanfaatkan untuk budidaya sayuran dan TOGA, serta meningkatnya pemahaman masyarakat mengenai pemanfaatan sampah plastik sebagai teknologi tepat guna.',
    iconName: 'Wrench',
  },
  {
    id: 'prog-16',
    title: 'TERARIUM: Pemanfaatan Barang Bekas sebagai Media Edukasi Ekosistem Mini dan Kepedulian Lingkungan',
    category: 'edukasi',
    status: 'rencana',
    description: 'Seni menanam dalam wadah kaca bekas untuk mengenalkan siklus air dan keseimbangan ekosistem mini.',
    fullDescription: 'Kegiatan edukatif bagi siswa-siswi SMP Negeri 6 Yogyakarta dalam merakit terarium menggunakan botol/toples kaca bekas guna memahami simulasi ekosistem mini tertutup serta memupuk kepedulian lingkungan.',
    date: 'Juli 2026 (Direncanakan)',
    location: 'SMP Negeri 6 Yogyakarta',
    coordinator: 'Chani',
    impact: 'Siswa mampu membuat terarium dari barang bekas serta memahami konsep ekosistem mini dan pentingnya menjaga lingkungan.',
    iconName: 'Globe',
  },
  {
    id: 'prog-17',
    title: 'Eco Movie: Pemutaran Film Wall-E',
    category: 'edukasi',
    status: 'rencana',
    description: 'Pemutaran film animasi Wall-E disertai diskusi pesan moral kelestarian bumi dan bahaya limbah.',
    fullDescription: 'Metode edukasi visual melalui pemutaran film Wall-E di sekolah untuk mengenalkan isu sampah anorganik global secara menyenangkan sekaligus merangsang aksi nyata menjaga kelestarian bumi.',
    date: 'Juli 2026 (Direncanakan)',
    location: 'SMP Negeri 6 Yogyakarta',
    coordinator: 'Chani',
    impact: 'Meningkatnya kesadaran lingkungan siswa melalui media audiovisual serta kemampuan mengidentifikasi pesan lingkungan dari film Wall-E.',
    iconName: 'Tv',
  },
  {
    id: 'prog-18',
    title: 'Eco-Enzyme: Workshop Edukatif Mengolah Sampah Dapur Menjadi Cairan Serbaguna',
    category: 'sampah',
    status: 'rencana',
    description: 'Fermentasi kulit buah dan sayur sisa menjadi larutan disinfektan dan pupuk cair ramah lingkungan.',
    fullDescription: 'Workshop edukatif bagi warga/ibu-ibu PKK untuk mengolah sampah organik rumah tangga (kulit buah/sisa sayur) menjadi cairan fermentasi serbaguna (Eco-Enzyme) yang bernilai manfaat tinggi dan ramah lingkungan.',
    date: 'Juli 2026 (Direncanakan)',
    location: 'Kelurahan Cokrodiningratan',
    coordinator: 'Chani',
    impact: 'Masyarakat/ibu PKK mampu membuat eco-enzyme secara mandiri dari sampah dapur organik dan memahami manfaatnya sebagai cairan serbaguna ramah lingkungan.',
    iconName: 'Droplets',
  },
];

export const FAQ_DATA: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'Siapa itu Sub-Unit 4 KKN-PPM UGM JAVATIS?',
    answer: 'Sub-Unit 4 merupakan bagian dari tim mahasiswa KKN-PPM Universitas Gadjah Mada (UGM) Unit JAVATIS periode II tahun 2026 yang diterjunkan khusus untuk mengabdi dan mendampingi warga di Kelurahan Cokrodiningratan, Jetis, Kota Yogyakarta dalam aspek lingkungan hidup, ekonomi sirkular, dan kesehatan.',
  },
  {
    id: 'faq-2',
    question: 'Apa tujuan utama dari program reaktivasi Bank Sampah oleh mahasiswa UGM?',
    answer: 'Tujuan utamanya adalah merevitalisasi operasional Bank Sampah pasca-pandemi melalui digitalisasi pencatatan (Excel/Spreadsheet) untuk akurasi data keuangan, serta memberikan edukasi pengemasan dan klasifikasi sampah anorganik agar harga jual ke pengepul dapat optimal dan transparan.',
  },
  {
    id: 'faq-3',
    question: 'Bagaimana metode Ember Tumpuk yang disosialisasikan KKN UGM bekerja?',
    answer: 'Ember tumpuk menggunakan dua ember plastik yang dipasang tumpuk atas-bawah. Ember atas berlubang kecil di dasarnya untuk menampung sampah organik basah dan tempat pembusukan, sementara ember bawah menampung tetesan cairan hasil pembusukan (lindi). Cairan lindi inilah yang difermentasikan menjadi Pupuk Organik Cair (POC) bernilai hara tinggi.',
  },
  {
    id: 'faq-4',
    question: 'Di mana peta spasial pariwisata hijau dan UMKM dapat diakses?',
    answer: 'Peta spasial digital interaktif buatan Sub-Unit 4 KKN UGM dapat diakses melalui scan QR Code yang tertera pada papan infografis utama di Balai RW 03 serta salinan fisiknya tersedia di perpustakaan kelurahan untuk keperluan administrasi dan kunjungan studi banding.',
  },
  {
    id: 'faq-5',
    question: 'Bagaimana warga Cokrodiningratan bisa memperoleh bantuan ember komposter atau rak vertikultur?',
    answer: 'Warga dapat berkoordinasi dengan Ketua RW atau perwakilan Kader PKK RW 03. Ember tumpuk percontohan dan modul rak vertikultur kayu didistribusikan secara gratis kepada kelompok RT sasaran prioritas yang aktif dalam pemeliharaan lingkungan selama masa KKN.',
  },
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Ibu Endang Rahayu',
    role: 'Ketua Bank Sampah RW 03 Cokrodiningratan',
    comment: 'Kami sangat bersyukur didampingi oleh adik-adik KKN UGM Sub-Unit 4. Pembukuan Bank Sampah kami yang tadinya ditulis manual di kertas, sekarang sudah tercatat rapi secara digital. Proses penimbangan pun jadi lebih cepat dan tidak membingungkan!',
    avatarSeed: 'endang',
  },
  {
    id: 'test-2',
    name: 'Bapak Slamet',
    role: 'Warga RT 11 Cokrodiningratan',
    comment: 'Lorong rumah saya sekarang jauh lebih sejuk dan asri berkat rak vertikultur modular kayu dari KKN UGM. Ibu-ibu di sini juga sangat senang bisa memetik sayur segar langsung di depan rumah untuk dimasak sehari-hari.',
    avatarSeed: 'slamet',
  },
  {
    id: 'test-3',
    name: 'Ibu Retno',
    role: 'Kader PKK RT 10 & Ibu Rumah Tangga',
    comment: 'Melalui penyuluhan ember tumpuk dari mahasiswa KKN JAVATIS, kami akhirnya mengerti cara mengolah sampah dapur tanpa berbau busuk. Kami malah mendapat bonus pupuk organik cair gratis yang sangat bagus untuk menyuburkan bunga pot.',
    avatarSeed: 'retno',
  },
];

export const MEMBERS_DATA: MemberItem[] = [
  {
    name: 'AMAN',
    prodi: 'S1 Agroteknologi',
    fakultas: 'Fakultas Pertanian',
    role: 'Koordinator Sub-Unit (Kormasub)',
    color: 'bg-brand-primary text-white',
    iconName: 'Award',
    desc: 'Memimpin koordinasi internal tim dan penyelarasan program kerja pemberdayaan lingkungan bersama masyarakat RW 03.'
  },
  {
    name: 'VADA',
    prodi: 'S1 Agronomi',
    fakultas: 'Fakultas Pertanian',
    role: 'Anggota',
    color: 'bg-brand-accent text-brand-deep',
    iconName: 'MapPin',
    desc: 'Mengelola administrasi digital, rekap data program, serta pemetaan spasial sebaran potensi kebun gizi kampung hijau.'
  },
  {
    name: 'RAYA',
    prodi: 'S1 Hukum',
    fakultas: 'Fakultas Hukum',
    role: 'Anggota',
    color: 'bg-brand-deep text-white',
    iconName: 'FileCheck',
    desc: 'Menyusun rancangan anggaran, logistik alat, serta memimpin aksi gotong royong biopori dan revitalisasi Bank Sampah.'
  },
  {
    name: 'CHANI',
    prodi: 'S1 Manajemen',
    fakultas: 'Fakultas Sosial dan Politik',
    role: 'Anggota',
    color: 'bg-teal-600 text-white',
    iconName: 'TrendingUp',
    desc: 'Menyusun sistem pembukuan keuangan mandiri untuk keberlanjutan Bank Sampah digital warga.'
  },
  {
    name: 'NATA',
    prodi: 'S1 Arkeologi',
    fakultas: 'Fakultas Ilmu Budaya',
    role: 'Anggota',
    color: 'bg-emerald-600 text-white',
    iconName: 'Sprout',
    desc: 'Mendesain rak vertikultur modular kayu, pembagian bibit TOGA, dan edukasi pupuk ember tumpuk.'
  },
  {
    name: 'GABY',
    prodi: 'S1 Teknologi Pangan',
    fakultas: 'Fakultas Teknologi Pertanian',
    role: 'Anggota',
    color: 'bg-indigo-600 text-white',
    iconName: 'Heart',
    desc: 'Menginisiasi program mengajar di SD terkait cuci tangan pakai sabun (CTPS) dan pola hidup sehat.'
  }
];
